name: Build x86_64 openwrt

on:
  workflow_dispatch:
    inputs:
      WRT_THEME:
        description: "默认主题"
        type: choice
        options:
          - "bootstrap"
          - "argon"
        required: true
        default: "argon"
      WRT_NAME:
        description: "主机名称"
        required: true
        type: string
        default: "IWRT"
      WRT_WIFI:
        description: "Wifi名称"
        required: true
        type: string
        default: "IAmWifi"
      WRT_IP:
        description: "默认访问IP"
        required: true
        type: string
        default: "192.168.15.1"

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  WRT_THEME: ${{inputs.WRT_THEME}}
  WRT_NAME: ${{inputs.WRT_NAME}}
  WRT_WIFI: ${{inputs.WRT_WIFI}}
  WRT_IP: ${{inputs.WRT_IP}}
  WRT_URL: https://github.com/openwrt/openwrt.git
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检查服务器性能
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo "CPU核心数量: $(nproc)"
          echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息:"
          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: 将存储库签出到运行器
        uses: actions/checkout@v4

      - name: 初始化环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          df -hT $PWD
          chmod 744 $GITHUB_WORKSPACE/scripts/init_env.sh
          $GITHUB_WORKSPACE/scripts/init_env.sh

      - name: 编译
        id: compile
        run: |
          df -hT $PWD
          LOG_DATE=$(date +'%Y-%m-%d %H%M')
          echo "LOG_DATE=${LOG_DATE}" >> $GITHUB_ENV
          chmod 744 $GITHUB_WORKSPACE/openwrt/build.sh
          $GITHUB_WORKSPACE/openwrt/build.sh 2>&1 | tee build_${LOG_DATE}.log
          cp -r $GITHUB_WORKSPACE/openwrt/build/bin $GITHUB_WORKSPACE/out
          useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H<br/>")
          echo "useVersionInfo=$useVersionInfo" >>$GITHUB_ENV
          echo "LAST_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DEVICE_NAME=x86_64" >>  $GITHUB_ENV
          echo "FILE_DATE=_$(date +'%Y-%m-%d %H%M')" >> $GITHUB_ENV

      - name: 上传编译日志
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_log_${LOG_DATE}
          path: build_${LOG_DATE}.log

      - name: 上传bin
        uses: actions/upload-artifact@v4
        if: steps.compile.outputs.status == 'success'
        with:
          name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: out

      - name: 文件打包
        id: organize
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cd $GITHUB_WORKSPACE/build/bin/targets/*/*
          rm -rf packages
          find . -type f ! -name '*.bin' -exec rm -f {} \;
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"
          echo "::set-output name=release_tag::$(date +"%Y-%m-%d %H%M")"

      - name: 上传固件
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}

      - name: Prepare release tag
        id: release_tag
        run: |
          DATE_PREFIX=$(date +%y%m%d)
          echo "::set-output name=date_prefix::${DATE_PREFIX}"

      - name: Process Input
        id: process
        run: echo "::set-output name=model_name::$(echo ${{ github.event.inputs.my-input }} | tr '_' '-')"
